### PR TITLE
[CLOUD-2542] - Running transaction recovery in environment where shared persistent volume is not available

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-2542
Signed-off-by: Ken Wills <kwills@redhat.com>

This re-reverses the template change that was merged ahead of verification on CD14 and completes the changes for CLOUD-2542.

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by luck3y** [comment]
@ochaloup FYI

**Comment by luck3y** [comment]
@bstansberry This just re-adds the template via a revert of a previous revert, so no additional changes.

**Comment by ochaloup** [comment]
@luck3y I would just mention that part of this PR is the fix for the CLOUD-3017. The returning back the template for CLOUD-2542 is obviously welcomed by me :)

btw. asj the fix CLOUD-3017 was involved I've got to be curious - what's the reasoning behind of adding the `publishNotReadyAddresses` to templates. What issue that solves regarding the deploymentconfigs?

**Comment by luck3y** [comment]
@ochaloup Oops, too many spinning plates here, that change shouldn't be part of this ... I'll fix.

**Comment by luck3y** [comment]
@ochaloup PR corrected, thanks and sorry for that.

FWIW the CLOUD-3017 change has to do with the headless services annotation being deprecated in upstream kubernetes, what used to be service.alpha.kubernetes.io/tolerate-unready-endpoints: true is replaced by the property: publishNotReadyAddresses: true.

This mainly affects clustering nodes being listed as available in k8s DNS before the first ready check has been passed.

Both the legacy annotation and the new attribute are in the 72 / CD templates.

**Comment by ochaloup** [comment]
@luck3y oh, I understand now. Thank you for explanation.

The PR is fine by me now, thanks.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
