### PR TITLE
Add EAP 7.1 image

### PR DESCRIPTION
**Pull request by douglaspalmer**

### CODE REVIEW

**Comment by goldmann** [comment]
Waiting for https://github.com/jboss-openshift/cct_module/pull/7 to be merged first.

**Comment by goldmann** [comment]
Can you please update README too?

**Comment by rcernich** [comment]
LGTM

**Review by rcernich — APPROVED** [review]
LGTM

**Comment by goldmann** [comment]
Please hold on, we'll need to make this a tech preview image. I'll work on this tomorrow.

**Comment by goldmann** [comment]
Merging this, I'll update the name later.

**Pull request merged**
