### PR TITLE
[CLOUD-3122] - EAP CD - OpenJDK 11 / UBI

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-3122
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by luck3y** [comment]
@bstansberry I left this at CD 16 for now, as introducing CD17 stuff when the artifact we're actually building with is really 16 seemed to be inconsistent. The only remaining changes for 17 needed is a module update in jboss-eap-7-image to provide the zip and then introducing a version 17.0 config module with standalone-openshift.xml in it. For 17.0 we should only have one config, and the default DB drivers should be dropped (mysql & postgres) from the config.

Also requires https://github.com/jboss-container-images/jboss-eap-modules/pull/117 for the config module.

**Comment by luck3y** [comment]
@jfdenise FYI

**Comment by bstansberry** [comment]
+1 re sticking to 16. My main goal was to get this branch onto JDK 11 / UBI 8. Upgrading the zip is a different task.

**Review by bstansberry — APPROVED** [review]

**Comment by bstansberry** [comment]
@luck3y LGTM

**Pull request merged**
