### PR TITLE
Update GitHub PR template

### PR DESCRIPTION
**Pull request by jmtd**
This adds or updates the Github PR template for this repository to reflect
the version in the master repository:

    https://github.com/jboss-container-images/github-pr-template

This Pull Request was auto generated by the scripts from the above repository.

### CODE REVIEW

**Review by goldmann — APPROVED** [review]

**Review by vhalbert — COMMENTED** [review]
Regarding:  Attached commits represent unit of work and are properly formatted
Is there a link to what the rules are on "properly formatted"

**Comment by goldmann** [comment]
Basically we're talking here about common sense, title should not be "Fix" or just a "WIP" or "tmp". Preferably there should be short title and loner description in the commit body, just regular Git best practices.

**Comment by vhalbert** [comment]
I think I was reading too deep into it.  I took the formatting rule to apply to what was actually committed, not the title or description.

**Comment by goldmann** [comment]
Oh, possibly :) Content of the commit is reviewed as part of the review process, so any mistakes there will be pointed out at that time, hopefully.

**Pull request merged**
