### PR TITLE
[CLOUD-3840] Added missing eap73 openj9-11 templates

### PR DESCRIPTION
**Pull request by dale-fu**
Signed-off-by: Dale Fu dafu@redhat.com

https://issues.redhat.com/browse/CLOUD-3840
Adding missing EAP 73 OpenJ9-11 templates that are used in the OpenShift EAP test suite.

### CODE REVIEW

**Comment by levivic** [comment]
Hi @luck3y , do you think you can merge this? I know we talked about moving the templates to another repo. But seems the EAP team is still using templates here.

**Comment by luck3y** [comment]
Hi @levivic Is the purpose of these templates to just provide the default image name? If so I think adding the entire set of templates for that is probably not such a good idea.

If you look at how we document it, users are directed to the other repo: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html/getting_started_with_jboss_eap_for_openshift_container_platform/build_run_java_app_s2i#import_imagestreams_templates

Which provides parameterized templates that can specify an image name, is this not sufficient?

FYI @jmesnil

**Comment by levivic** [comment]
Hi @luck3y, I think the reason why Dale is adding the templates here is because this repo is the default one used by the x86 QE test suite, which is shared with us for s390x. So we are trying to align our test towards x86 test, with minimal changes to the test suite.  Let me double check with Dale to see if we can modify the QE test suite to point to the other repo.

**Comment by dale-fu** [comment]
Hi @luck3y, I talked to some members on the EAP QE team regarding this. I will move my work to the other template repo you created, https://github.com/jboss-container-images/jboss-eap-openshift-templates/tree/eap73-dev. They also mentioned to me that they currently don't have plans to move the test suite to that new repo and they will continue to use this one for Intel. I will still need to make some modifications to get it working on the other repo, but they mentioned that they are okay with me making some modifications to the templates on the other repo for openj9-11. 

I will close this PR and continue working on the other repo.

**Pull request closed without merging**
