### PR TITLE
[CLOUD-3227] - Rename templates to avoid collision with 7.2.x

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-3227
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by bstansberry** [comment]
@luck3y Does this need a docs update too?

**Comment by luck3y** [comment]
@bstansberry These names are what we used in the migration doc, so docs should already be sorted.

**Review by bstansberry — CHANGES_REQUESTED** [review]
@luck3y My previous comment about docs was referring to https://github.com/jboss-container-images/jboss-eap-7-openshift-image/tree/eap72-openjdk11-ubi8-dev/docs

**Comment by luck3y** [comment]
@bstansberry Oh, thanks yeah, sorry forgot about those, will update.

**Comment by luck3y** [comment]
@bstansberry Docs updated

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
