### PR TITLE
[CLOUD-2907] review usage of hidden label on EAP CD templates.

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-2907

Since we only import a few templates into OSO, we may as well have all of the rest visible if a user imports them manually.

Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by bstansberry** [comment]
@luck3y Let's chat tomorrow about how this relates to https://github.com/openshift/openshift-ansible/commits/master/roles/openshift_examples/files/examples/latest/xpaas-templates

**Comment by luck3y** [comment]
@bstansberry OK, I'll ping you. FWIW, I think its appropriate for most, if not all of these to be unhidden even in this case.

However, I think we have a different case to be made as to the actual templates we ship in OKD etc. Some I think we should possibly omit.

**Comment by bstansberry** [comment]
We still never chatted. :) Maybe tomorrow...

**Comment by luck3y** [comment]
Yeah, sorry I got a bit involved in the clustering tests. I'll 100% ping you tomorrow.

**Comment by luck3y** [comment]
Updated to hide any non-persistent DB templates and SSO (this was hidden before too).

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
