### PR TITLE
CLOUD-2758 - [EAP71] Update jgroups AUTH and SYM_ENCRYPT to use non deprecated configurations

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-2758
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by luck3y** [comment]
7.1 version of https://github.com/jboss-container-images/jboss-eap-7-openshift-image/pull/134

**Comment by luck3y** [comment]
@bstansberry This one has both QE and dev approval, but it still needs a review to unblock it.

**Review by bstansberry — APPROVED** [review]
@luck3y Seems fine, good to go so long as the qe approval was meant for 7.1 as well.

**Comment by luck3y** [comment]
@bstansberry Yep, @maschmid gave them both the thumbs up in a jira comment.

**Pull request merged**
