### PR TITLE
[Cloud 2413] move db drivers eap cd

### PR DESCRIPTION
**Pull request by jmtd**
https://issues.jboss.org/browse/CLOUD-2413

### CODE REVIEW

**Review by luck3y — APPROVED** [review]

**Comment by luck3y** [comment]
@jmtd As a final check, do you see anything in https://github.com/jboss-container-images/jboss-eap-modules that might also need updating? I'll have a look too.

**Comment by luck3y** [comment]
I've checked over https://github.com/jboss-container-images/jboss-eap-modules and I don't see anything additional. 

I would like to merge this ASAP so we can start moving other modules around though.

**Comment by luck3y** [comment]
@jmtd I'm not clear on the status of this, we need cct_modules merged first, right?

**Comment by jmtd** [comment]
That’s right

**Pull request merged**
