### PR TITLE
[CLOUD-4857] Runtime image incorrectly sets JBOSS_MODULES_SYSTEM_PKGS to include org.jboss.logmanager

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.redhat.com/browse/CLOUD-3857
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Review by jfdenise — APPROVED** [review]
@luck3y , that is bound to this change in wildfly-cekit-modules right? : https://github.com/wildfly/wildfly-cekit-modules/commit/496984ddd50faaaa76b6bad87b0eaa16b5e5948b

**Review by jmesnil — COMMENTED** [review]
looks good to me but I defer to @jamezp for the approval.

**Review by jamezp — APPROVED** [review]
This looks good and makes sense to me as the log manager is no longer on the boot class path.

**Comment by luck3y** [comment]
> @luck3y , that is bound to this change in wildfly-cekit-modules right? : [wildfly/wildfly-cekit-modules@496984d](https://github.com/wildfly/wildfly-cekit-modules/commit/496984ddd50faaaa76b6bad87b0eaa16b5e5948b)

Correct yes, it was a bit of a pain to track it down, since the builder image worked fine & it would only fail when using templates etc in OCP.

**Comment by jfdenise** [comment]
Yes, well done! I should have logged something for EAP at the time I merged it for wildfly-s2i.

**Comment by luck3y** [comment]
@jfdenise No worries, James remembered and gave me the clue I needed :)

**Pull request merged**
