### PR TITLE
CLOUD-2913 - switch EAP 7.2 to use SSO 7.3 adapters

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.jboss.org/browse/CLOUD-2913
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by iankko** [comment]
@luck3y LGTM, ACK

**Comment by bstansberry** [comment]
This is fine to merge once the SSO 7.3 release is done (if it's not already.)

**Comment by luck3y** [comment]
SSO 7.3 is release, so we can merge this.

**Review by bstansberry — APPROVED** [review]

**Comment by luck3y** [comment]
Tested with 7.2  w SSO running on OSO and works fine.

**Pull request merged**
