### PR TITLE
update imagestreams to registry.redhat.io

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@goldmann these changes are needed for the new registry. i've submitted the PR against the branch that openshift/library is currently pulling from, but if you have an upstream dev branch, these changes need to be made there too.

**Comment by luck3y** [comment]
@bparees Is this just for images on OSO, or all images? I can take care of updating the rest of the EAP images if its all of them.

**Comment by bparees** [comment]
@luck3y anything that's pulled from registry.access.redhat.com needs to change, whether it's used in OSO or OCP.

i've already opened PRs for every imagestream that's being pulled into openshift/library today, i think, but by all means if i've missed something feel free.  Note that the local reference policy change is critical.

**Comment by bparees** [comment]
you can see everything i have open here: 
https://github.com/search?q=type%3Apr+author%3Abparees+is%3Aopen

**Comment by luck3y** [comment]
@bparees Thanks Ben, I'll update the upstreams etc for dev branches etc and get the new 7.2 stuff updated too.

**Comment by luck3y** [comment]
I'm going to close this in favor of: https://github.com/jboss-container-images/jboss-eap-7-openshift-image/pull/126 which we'll merge to -dev then cherry pick to the release branch.

**Pull request closed without merging**
