### PR TITLE
[WIP] Add ARQ tests

### PR DESCRIPTION
**Pull request by goldmann**
https://issues.jboss.org/browse/CLOUD-2732

See commit details for more information.

### CODE REVIEW

**Review by luck3y — APPROVED** [review]

**Comment by luck3y** [comment]
Thanks for this Marek! Much appreciated.

**Comment by goldmann** [comment]
Oh well, it was a WIP :)

**Comment by luck3y** [comment]
Oh, I just noticed the WIP, sorry! Want me to revert?

**Comment by goldmann** [comment]
Nah, we should be fine.

**Pull request merged**
